# Generated by Django 4.2b1 on 2023-03-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='urls_ebay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, verbose_name='Urls Ebay')),
                ('proxy', models.CharField(max_length=250, verbose_name='Urls Ebay')),
                ('nameProfile', models.CharField(max_length=250, unique=True, verbose_name='Name Profile')),
            ],
            options={
                'verbose_name': 'Urls Ebay',
                'verbose_name_plural': 'Urls Ebay',
            },
        ),
    ]
