# Generated by Django 4.2b1 on 2023-03-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_urls_ebay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls_ebay',
            name='proxy',
            field=models.CharField(max_length=250, verbose_name='Proxy'),
        ),
    ]
